# Generated by Django 3.1.2 on 2020-10-26 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0001_inititialmigration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='comments',
        ),
    ]
